fix: Perform the last action with the column name modified.
sapientml/core pull request #42
Opened 2023-12-12 06:48 UTC by tashiro-akira

@AkiraUra @kimusaku 
Fix target column names to revert after removing special characters.
This fix is necessary to address the preprocess issue https://github.com/sapientml/preprocess/issues/8.
Please check.

2024-01-05 07:47 UTC, AkiraUra requested changes
Could you consider my comments?

2024-01-05 07:47 UTC, AkiraUra commented on sapientml_core/generator.py
>              pipeline.predict = code_block.predict + pipeline.predict
How about the following code?

```python
            if "cols_has_symbols" in pipeline.test:
                pipeline.test = pipeline.test.replace('perm_df.to_csv', 'perm_df.rename(columns=rename_symbol_cols).to_csv')
                def replace_targets(match_obj):
                    return match_obj[0].replace('TARGET_COLUMNS', "[rename_symbol_cols.get(v, v) for v in TARGET_COLUMNS]")
                pat = r"prediction = pd.DataFrame\(y_prob, columns=.?TARGET_COLUMNS.*, index=feature_test.index\)"
                pipeline.test = pat.sub(replace_targets, pipeline.test)
                pipeline.predict = pat.sub(replace_targets, pipeline.predict)
            pipeline.validation = code_block.validation + pipeline.validation
            pipeline.test = code_block.test + pipeline.test
            pipeline.train = code_block.train + pipeline.train
            pipeline.predict = code_block.predict + pipeline.predict
```

2024-01-05 07:47 UTC, AkiraUra commented on sapientml_core/templates/other_templates/permutation_importance.py.jinja
I don't think these changes are necessary.

2024-01-05 07:47 UTC, AkiraUra commented on sapientml_core/templates/other_templates/prediction_result.py.jinja
I don't think these changes are necessary.

2024-01-11 07:24 UTC, tashiro-akira commented
Reflected the content of the review.
Undid unnecessary modifications.

2024-06-03 06:23 UTC, AkiraUra reviewed
Thank you for the PR. The code of `rename_dict` is duplicated from the preprocess one.
Could you consider a way of removing the duplication?

2024-06-28 02:24 UTC, tashiro-akira commented
Changed branches and issued new pull requests to capture core and preprocess integration fixes.
PR:https://github.com/sapientml/core/pull/78

2024-07-01 06:55 UTC, tashiro-akira commented
Changed branches and issued new pull requests to capture core and preprocess integration fixes.

The correspondence of the comment is also described in the new pull request.
PR:https://github.com/sapientml/core/pull/78

2024-07-01 06:55 UTC, closed without merging